#skip submodules:
#https://github.com/ardumont/dot-files/blob/master/.travis.yml
#https://github.com/travis-ci/travis-yaml/blob/master/spec/nodes/git_spec.rb
#  - gxmessage libnotify-bin gmail-notify curl vim-gtk pv cowsay toilet figlet sox libsox-fmt-mp3
before_install:
  - ./.install_deps.sh
   
language: bash
git:
  submodules: false
before_script: ./LIB/install.sh
script:       ./present.sh
after_script: bash #-c 'echo bye' 
branches:
  only:
      - develop
env:
  global:
      - url_travis="http://docs.travis-ci.com/user/build-configuration/"
  matrix:
      - USE_NETWORK=false
notifications:
  email:
      - advance.linux2@gmail.com       
